//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontesERP.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MontesERPEntities : DbContext
    {
        public MontesERPEntities()
            : base("name=MontesERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComprobanteDeDiario> ComprobanteDeDiario { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<DetalleComprobanteDeDiario> DetalleComprobanteDeDiario { get; set; }
        public virtual DbSet<GrupoCuenta> GrupoCuenta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<SubCuenta> SubCuenta { get; set; }
        public virtual DbSet<SubGrupoCuenta> SubGrupoCuenta { get; set; }
    }
}
