//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontesERP.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGrupoCuenta
    {
        public SubGrupoCuenta()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public int IdSubGrupoCuenta { get; set; }
        public int IdGrupoCuenta { get; set; }
        public string NombreSubGrupoCuenta { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        public virtual GrupoCuenta GrupoCuenta { get; set; }
    }
}
