//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontesERP.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MontesERPEntities : DbContext
    {
        public MontesERPEntities()
            : base("name=MontesERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<ComprobanteDeDiario> ComprobanteDeDiarios { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<DetalleComprobanteDeDiario> DetalleComprobanteDeDiarios { get; set; }
        public virtual DbSet<GrupoCuenta> GrupoCuentas { get; set; }
        public virtual DbSet<SubCuenta> SubCuentas { get; set; }
        public virtual DbSet<SubGrupoCuenta> SubGrupoCuentas { get; set; }
    }
}
