//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontesERP.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCuenta
    {
        public SubCuenta()
        {
            this.DetalleComprobanteDeDiarios = new HashSet<DetalleComprobanteDeDiario>();
        }
    
        public int IdSubCuenta { get; set; }
        public int IdCuenta { get; set; }
        public string NombreSubCuenta { get; set; }
        public Nullable<decimal> debeAnterior { get; set; }
        public Nullable<decimal> haberAnterior { get; set; }
        public Nullable<decimal> debeActual { get; set; }
        public Nullable<decimal> haberActual { get; set; }
        public Nullable<decimal> saldo { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<DetalleComprobanteDeDiario> DetalleComprobanteDeDiarios { get; set; }
    }
}
